<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\karel-cpp\karel-cpp.vcxproj" />
    <ProjectReference Include="..\karelui\karelui.csproj" />
    <ProjectReference Include="..\karelvm\karelvm.csproj" />
  </ItemGroup>
</Project>
